### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by tuxredux** [stevematney/redgreenunittests#8]
```bash
$ python functional_tests.py
Traceback (most recent call last):
  File "functional_tests.py", line 62, in <module>
    unittest.main()
  File "/home/user/Projects/.sandbox/python-tdd-book/env/lib/python3.6/site-packages/redgreenunittest/main.py", line 78, in __init__
    if isinstance(module, basestring):
NameError: name 'basestring' is not defined
```

**Comment by stevematney** [comment]
Hi @nathanurwin! Thanks for the report! This is all really helpful. Would it be possible to provide a very small test and code example to duplicate this error?

**Comment by nathanurwin** [comment]
Hey @stevematney :wave: Glad to help! For sure, check out the [functional_tests.py](https://www.obeythetestinggoat.com/book/chapter_02_unittest.html#_the_python_standard_library_s_unittest_module). I'm farther along in the tutorial now where instead of calling `python functional_tests.py` the tests are ran through the Django test runner, i.e. `python manage.py test functional_tests` and everything is working great! :ok_hand:
